
data_info_dict = {
    'MAYO': {'data_path': '/datasets/MAYO/group_data',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 1000,
        'channel': 1,
        'seq_len': 3,
        'downstream': 'disorder',
    },
    'FNUSA': {'data_path': '/datasets/FNUSA/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 1000,
        'channel': 1,
        'seq_len': 3,
        'downstream': 'disorder',
    },
    'CHBMIT': {'data_path': '/datasets/CHBMIT/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 23,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'SleepEDFx': {
        'data_path': '/datasets/SleepEDFx/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'sfreq': 100,
        'channel': 1,
        'seq_len': 30,
        'downstream': 'disorder',
    },
    'ADFD':{
        'data_path': '/datasets/ADFD/group_data_AD',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'ADHD_Adult':{
        'data_path': '/datasets/Adults_ADHD/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 2,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'ADHD_Child':{
        'data_path': '/datasets/Child_ADHD/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 128,
        'channel': 19,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'Depression_122_BDI':{
        'data_path': '/datasets/Depression_122/group_data_BDI',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 64,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'Depression_122_STAI':{
        'data_path': '/datasets/Depression_122/group_data_STAI',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 3,
        'sfreq': 250,
        'channel': 64,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'Schizophrenia_28':{
        'data_path': '/datasets/EEG_schizophrenia/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'MPHCE_mdd':{
        'data_path': '/datasets/MPHCE/group_data_mdd',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'MPHCE_state':{
        'data_path': '/datasets/MPHCE/group_data_state',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 3,
        'sfreq': 256,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'SEED_IV':{
        'data_path': '/datasets/SEED_IV/group_data',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 200,
        'channel': 62,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'SD_71':{
        'data_path': '/datasets/Sleep_Deprivation/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 61,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'EEGMat':{
        'data_path': '/datasets/EEGMat/group_data',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'Motor imagine',
    },
    'DEAP':{
        'data_path': '/datasets/DEAP/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 128,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'emotion',
    },
    'EEGMMIDB_R':{
        'data_path': '/datasets/EEGMMIDB/group_data_R',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 160,
        'channel': 64,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'EEGMMIDB_I':{
        'data_path': '/datasets/EEGMMIDB/group_data_I',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 160,
        'channel': 64,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'UCSD_ON': {'data_path': '/datasets/UCSD/group_data_on',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'UCSD_OFF': {'data_path': '/datasets/UCSD/group_data_off',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'ISRUC': {'data_path': '/datasets/ISRUC/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'sfreq': 200,
        'channel': 6,
        'seq_len': 30,
        'downstream': 'disorder',
    },
    'AD-65': {'data_path': '/datasets/ADFD/group_data_AD',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'BCI-2a': {'data_path': '/datasets/BCICIV_2a/group_data',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 250,
        'channel': 22,
        'seq_len': 3,
        'downstream': 'Motor imagine',
    },
    'Chisco_read': {'data_path': '/datasets/Chisco/group_data_read',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 39,
        'sfreq': 500,
        'channel': 122,
        'seq_len': 3,
        'downstream': 'concept',
        'label_path': '/datasets/Chisco/classnumber.json',
    },
    'Chisco_imagine': {'data_path': '/datasets/Chisco/group_data_imagine',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 39,
        'sfreq': 500,
        'channel': 122,
        'seq_len': 3,
        'downstream': 'concept',
        'label_path': '/datasets/Chisco/classnumber.json',
    },
    'HUP-SEEG': {'data_path': '/datasets/HUP-SEEG/group_data',
        'group_num': 37,
        'split': [20, 8, 9],
        'various_ch_num': True,
        'n_class': 2,
        'sfreq': 512,
        'channel': 0,
        'seq_len': 2,
        'downstream': 'disorder',
    }, 
    'HUP-ECoG': {'data_path': '/datasets/HUP-ECoG/group_data',
        'group_num': 20,
        'split': [12, 4, 4],
        'various_ch_num': True,
        'n_class': 2,
        'sfreq': 512,
        'channel': 0,
        'seq_len': 2,
        'downstream': 'disorder',
    }, 
    'SWEC': {'data_path': '/datasets/SWEC/group_data',
        'group_num': 68,
        'split': [40, 14, 14],
        'various_ch_num': True,
        'n_class': 2,
        'sfreq': 512,
        'channel': 0,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'Cogitate-CF-ECoG': {'data_path': '/datasets/Cogitate-CF-ECoG/group_data',
        'group_num': 11,
        'split': [7, 2, 2],
        'various_ch_num': True,
        'n_class': 2,
        'sfreq': 512,
        'channel': 0,
        'seq_len': 2,
        'downstream': 'visual perception',
    },
    'Cogitate-CF-SEEG': {'data_path': '/datasets/Cogitate-CF-SEEG/group_data',
        'group_num': 19,
        'split': [11, 4, 4],
        'various_ch_num': True,
        'n_class': 2,
        'sfreq': 512,
        'channel': 0,
        'seq_len': 2,
        'downstream': 'visual perception',
    },
}
